### ISSUE TITLE
El enlace "✨ ¡Presentamos los proyectos del Hackathon #Somos600M! ✨" en https://somosnlp.org/hackathon/bases no funciona

### ISSUE THREAD

**Issue by tom9358** [somosnlp/somosnlp.org#265]
Me interesaría mucho ver sus proyectos, pero obtengo un error 404
Pasos para reproducirlo:
Vaya a https://somosnlp.org/hackathon/bases
Haga clic en https://somosnlp.org/pages/blog/proyectos-hackathon-2024.md

**Comment by mariagrandury** [comment]
El enlace correcto era https://somosnlp.org/blog/proyectos-hackathon-2024.md

Muchas gracias por avisar! Arreglado ✅

**Comment by tom9358** [comment]
Casi funciona! La URL correcta no tiene ".md". Gracias por la respuesta súper rápida :)
